//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebitoInmediatoServiceItau
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato", ConfigurationName = "DebitoInmediatoServiceItau.DebitoInmediato")]
    public interface DebitoInmediato
    {

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<DebitoInmediatoServiceItau.RegistrarPublicacionResponse> RegistrarPublicacionAsync(DebitoInmediatoServiceItau.RegistrarPublicacionRequest request);

        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<DebitoInmediatoServiceItau.ConsultarEstadoResponse> ConsultarEstadoAsync(DebitoInmediatoServiceItau.ConsultarEstadoRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class headerType
    {

        private clave_mensajeType clave_mensajeField;

        private info_requerimientoType info_requerimientoField;

        private seguridadType seguridadField;

        private transaccionType transaccionField;

        private adicionalType[] adicionalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public clave_mensajeType clave_mensaje
        {
            get
            {
                return this.clave_mensajeField;
            }
            set
            {
                this.clave_mensajeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public info_requerimientoType info_requerimiento
        {
            get
            {
                return this.info_requerimientoField;
            }
            set
            {
                this.info_requerimientoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public seguridadType seguridad
        {
            get
            {
                return this.seguridadField;
            }
            set
            {
                this.seguridadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public transaccionType transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adicional", Order = 4)]
        public adicionalType[] adicional
        {
            get
            {
                return this.adicionalField;
            }
            set
            {
                this.adicionalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class clave_mensajeType
    {

        private string id_requerimientoField;

        private string host_origenField;

        private string servicioField;

        private string id_canalField;

        private string id_mensaje_esbField;

        private string id_orquestacion_esbField;

        private string id_transaccion_proField;

        private string id_operadorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string id_requerimiento
        {
            get
            {
                return this.id_requerimientoField;
            }
            set
            {
                this.id_requerimientoField = value;
            }
        }

        /// <remarks/>
        public string host_origen
        {
            get
            {
                return this.host_origenField;
            }
            set
            {
                this.host_origenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string servicio
        {
            get
            {
                return this.servicioField;
            }
            set
            {
                this.servicioField = value;
            }
        }

        /// <remarks/>
        public string id_canal
        {
            get
            {
                return this.id_canalField;
            }
            set
            {
                this.id_canalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id_mensaje_esb
        {
            get
            {
                return this.id_mensaje_esbField;
            }
            set
            {
                this.id_mensaje_esbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id_orquestacion_esb
        {
            get
            {
                return this.id_orquestacion_esbField;
            }
            set
            {
                this.id_orquestacion_esbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id_transaccion_pro
        {
            get
            {
                return this.id_transaccion_proField;
            }
            set
            {
                this.id_transaccion_proField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string id_operador
        {
            get
            {
                return this.id_operadorField;
            }
            set
            {
                this.id_operadorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado")]
    public partial class ConsultarEstadoResponseType
    {

        private string codigoField;

        private string estadoField;

        private string descripcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "bodyResponseType", Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado")]
    public partial class bodyResponseType1
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsultarEstadoResponse", typeof(ConsultarEstadoResponseType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(ExcepcionType), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion_err")]
    public partial class ExcepcionType
    {

        private DetalleType detalleField;

        private DetalleExcepcionType[] detalleExtendidoField;

        private DatoAdicionalType[] datosAdicionalesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public DetalleType detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("excepcion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DetalleExcepcionType[] detalleExtendido
        {
            get
            {
                return this.detalleExtendidoField;
            }
            set
            {
                this.detalleExtendidoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("datoAdicional", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public DatoAdicionalType[] datosAdicionales
        {
            get
            {
                return this.datosAdicionalesField;
            }
            set
            {
                this.datosAdicionalesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion_err")]
    public partial class DetalleType
    {

        private string codigoField;

        private string subCodigoField;

        private string descripcionField;

        private string origenField;

        private string tipoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string subCodigo
        {
            get
            {
                return this.subCodigoField;
            }
            set
            {
                this.subCodigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion_err")]
    public partial class DetalleExcepcionType
    {

        private string subCodigoField;

        private string descripcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string subCodigo
        {
            get
            {
                return this.subCodigoField;
            }
            set
            {
                this.subCodigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion_err")]
    public partial class DatoAdicionalType
    {

        private string nombreField;

        private string valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado")]
    public partial class ConsultarEstadoType
    {

        private string numeroCuitField;

        private string numeroCBUField;

        private string codigoField;

        private string codigoOperacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string numeroCuit
        {
            get
            {
                return this.numeroCuitField;
            }
            set
            {
                this.numeroCuitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string numeroCBU
        {
            get
            {
                return this.numeroCBUField;
            }
            set
            {
                this.numeroCBUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string codigoOperacion
        {
            get
            {
                return this.codigoOperacionField;
            }
            set
            {
                this.codigoOperacionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "bodyRequest", Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado")]
    public partial class bodyRequest1
    {

        private ConsultarEstadoType consultarEstadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ConsultarEstadoType ConsultarEstado
        {
            get
            {
                return this.consultarEstadoField;
            }
            set
            {
                this.consultarEstadoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class RegistrarPublicacionResponseType
    {

        private string codigoField;

        private string codigoOperacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string codigoOperacion
        {
            get
            {
                return this.codigoOperacionField;
            }
            set
            {
                this.codigoOperacionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class bodyResponseType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(ExcepcionType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RegistrarPublicacionResponse", typeof(RegistrarPublicacionResponseType), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class detalle
    {

        private string conceptoField;

        private string usoInternoField;

        private string comprobanteField;

        private string descripcionField;

        private decimal importeField;

        private string monedaField;

        private string recurrenciaField;

        private decimal montoPeriodoField;

        private bool montoPeriodoFieldSpecified;

        private string cantidadOperacionesPeriodoField;

        private string periodoField;

        private string fechaVencimientoField;

        private string horaVencimientoField;
        private string claveExternaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string concepto
        {
            get
            {
                return this.conceptoField;
            }
            set
            {
                this.conceptoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string usoInterno
        {
            get
            {
                return this.usoInternoField;
            }
            set
            {
                this.usoInternoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string comprobante
        {
            get
            {
                return this.comprobanteField;
            }
            set
            {
                this.comprobanteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string recurrencia
        {
            get
            {
                return this.recurrenciaField;
            }
            set
            {
                this.recurrenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public decimal montoPeriodo
        {
            get
            {
                return this.montoPeriodoField;
            }
            set
            {
                this.montoPeriodoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoPeriodoSpecified
        {
            get
            {
                return this.montoPeriodoFieldSpecified;
            }
            set
            {
                this.montoPeriodoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 8)]
        public string cantidadOperacionesPeriodo
        {
            get
            {
                return this.cantidadOperacionesPeriodoField;
            }
            set
            {
                this.cantidadOperacionesPeriodoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string periodo
        {
            get
            {
                return this.periodoField;
            }
            set
            {
                this.periodoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string fechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string horaVencimiento
        {
            get
            {
                return this.horaVencimientoField;
            }
            set
            {
                this.horaVencimientoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string claveExterna
        {
            get
            {
                return this.claveExternaField;
            }
            set
            {
                this.claveExternaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class datosComprador
    {

        private string numeroCuitField;

        private string numeroCBUField;

        private string aliasDebitoField;

        private string codigoField;

        private string razonSocialField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string numeroCuit
        {
            get
            {
                return this.numeroCuitField;
            }
            set
            {
                this.numeroCuitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string numeroCBU
        {
            get
            {
                return this.numeroCBUField;
            }
            set
            {
                this.numeroCBUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string aliasDebito
        {
            get
            {
                return this.aliasDebitoField;
            }
            set
            {
                this.aliasDebitoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class datosVendedor
    {

        private string numeroCuitField;

        private string numeroCBUField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string numeroCuit
        {
            get
            {
                return this.numeroCuitField;
            }
            set
            {
                this.numeroCuitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string numeroCBU
        {
            get
            {
                return this.numeroCBUField;
            }
            set
            {
                this.numeroCBUField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class RegistrarPublicacionType
    {

        private datosVendedor datosVendedorField;

        private datosComprador datosCompradorField;

        private detalle detalleField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public datosVendedor datosVendedor
        {
            get
            {
                return this.datosVendedorField;
            }
            set
            {
                this.datosVendedorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public datosComprador datosComprador
        {
            get
            {
                return this.datosCompradorField;
            }
            set
            {
                this.datosCompradorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public detalle detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion")]
    public partial class bodyRequest
    {

        private RegistrarPublicacionType registrarPublicacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public RegistrarPublicacionType RegistrarPublicacion
        {
            get
            {
                return this.registrarPublicacionField;
            }
            set
            {
                this.registrarPublicacionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class adicionalType
    {

        private string claveField;

        private string valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class transaccionType
    {

        private string id_estadoField;

        private string estadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public string id_estado
        {
            get
            {
                return this.id_estadoField;
            }
            set
            {
                this.id_estadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class passwordtokenType
    {

        private string id_usuarioField;

        private string claveField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string id_usuario
        {
            get
            {
                return this.id_usuarioField;
            }
            set
            {
                this.id_usuarioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class tokenType
    {

        private passwordtokenType passwordtokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public passwordtokenType passwordtoken
        {
            get
            {
                return this.passwordtokenField;
            }
            set
            {
                this.passwordtokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class seguridadType
    {

        private tokenType tokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public tokenType token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.itau.com.ar/integracion")]
    public partial class info_requerimientoType
    {

        private string id_organizacionField;

        private string codigo_sucursalField;

        private string numero_terminalField;

        private string cod_operacionField;

        private string fechahora_mensajeField;

        private string zona_horariaField;

        private string fechahora_mensaje_esbField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string id_organizacion
        {
            get
            {
                return this.id_organizacionField;
            }
            set
            {
                this.id_organizacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string codigo_sucursal
        {
            get
            {
                return this.codigo_sucursalField;
            }
            set
            {
                this.codigo_sucursalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 2)]
        public string numero_terminal
        {
            get
            {
                return this.numero_terminalField;
            }
            set
            {
                this.numero_terminalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string cod_operacion
        {
            get
            {
                return this.cod_operacionField;
            }
            set
            {
                this.cod_operacionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string fechahora_mensaje
        {
            get
            {
                return this.fechahora_mensajeField;
            }
            set
            {
                this.fechahora_mensajeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 5)]
        public string zona_horaria
        {
            get
            {
                return this.zona_horariaField;
            }
            set
            {
                this.zona_horariaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 6)]
        public string fechahora_mensaje_esb
        {
            get
            {
                return this.fechahora_mensaje_esbField;
            }
            set
            {
                this.fechahora_mensaje_esbField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RequestMessage", WrapperNamespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/request", IsWrapped = true)]
    public partial class RegistrarPublicacionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/request", Order = 0)]
        public DebitoInmediatoServiceItau.headerType header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/request", Order = 1)]
        public DebitoInmediatoServiceItau.bodyRequest body;

        public RegistrarPublicacionRequest()
        {
        }

        public RegistrarPublicacionRequest(DebitoInmediatoServiceItau.headerType header, DebitoInmediatoServiceItau.bodyRequest body)
        {
            this.header = header;
            this.body = body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResponseMessage", WrapperNamespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/response", IsWrapped = true)]
    public partial class RegistrarPublicacionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/response", Order = 0)]
        public DebitoInmediatoServiceItau.headerType header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/registrarpublicacion/response", Order = 1)]
        public DebitoInmediatoServiceItau.bodyResponseType body;

        public RegistrarPublicacionResponse()
        {
        }

        public RegistrarPublicacionResponse(DebitoInmediatoServiceItau.headerType header, DebitoInmediatoServiceItau.bodyResponseType body)
        {
            this.header = header;
            this.body = body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RequestMessage", WrapperNamespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/request", IsWrapped = true)]
    public partial class ConsultarEstadoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/request", Order = 0)]
        public DebitoInmediatoServiceItau.headerType header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/request", Order = 1)]
        public DebitoInmediatoServiceItau.bodyRequest1 body;

        public ConsultarEstadoRequest()
        {
        }

        public ConsultarEstadoRequest(DebitoInmediatoServiceItau.headerType header, DebitoInmediatoServiceItau.bodyRequest1 body)
        {
            this.header = header;
            this.body = body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResponseMessage", WrapperNamespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/response", IsWrapped = true)]
    public partial class ConsultarEstadoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/response", Order = 0)]
        public DebitoInmediatoServiceItau.headerType header;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.itau.com.ar/integracion/debitoinmediato/consultarestado/response", Order = 1)]
        public DebitoInmediatoServiceItau.bodyResponseType1 body;

        public ConsultarEstadoResponse()
        {
        }

        public ConsultarEstadoResponse(DebitoInmediatoServiceItau.headerType header, DebitoInmediatoServiceItau.bodyResponseType1 body)
        {
            this.header = header;
            this.body = body;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface DebitoInmediatoChannel : DebitoInmediatoServiceItau.DebitoInmediato, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class DebitoInmediatoClient : System.ServiceModel.ClientBase<DebitoInmediatoServiceItau.DebitoInmediato>, DebitoInmediatoServiceItau.DebitoInmediato
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public DebitoInmediatoClient() :
                base(DebitoInmediatoClient.GetDefaultBinding(), DebitoInmediatoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DebitoInmediatoSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DebitoInmediatoClient(EndpointConfiguration endpointConfiguration) :
                base(DebitoInmediatoClient.GetBindingForEndpoint(endpointConfiguration), DebitoInmediatoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DebitoInmediatoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(DebitoInmediatoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DebitoInmediatoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(DebitoInmediatoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DebitoInmediatoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<DebitoInmediatoServiceItau.RegistrarPublicacionResponse> RegistrarPublicacionAsync(DebitoInmediatoServiceItau.RegistrarPublicacionRequest request)
        {
            return base.Channel.RegistrarPublicacionAsync(request);
        }

        public System.Threading.Tasks.Task<DebitoInmediatoServiceItau.ConsultarEstadoResponse> ConsultarEstadoAsync(DebitoInmediatoServiceItau.ConsultarEstadoRequest request)
        {
            return base.Channel.ConsultarEstadoAsync(request);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebitoInmediatoSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebitoInmediatoSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://iibhomo.sis.ad.bia.itau/internet/debitoinmediato");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DebitoInmediatoClient.GetBindingForEndpoint(EndpointConfiguration.DebitoInmediatoSOAP);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DebitoInmediatoClient.GetEndpointAddress(EndpointConfiguration.DebitoInmediatoSOAP);
        }

        public enum EndpointConfiguration
        {

            DebitoInmediatoSOAP,
        }
    }
}
