//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivosCmlServiceItau
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CML/ARCHIVOSCML", ConfigurationName="ArchivosCmlServiceItau.ARCHIVOSCML")]
    public interface ARCHIVOSCML
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosSolicitudResponse1> archivosSolicitudAsync(ArchivosCmlServiceItau.archivosSolicitudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosPublicacionResponse1> archivosPublicacionAsync(ArchivosCmlServiceItau.archivosPublicacionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CML/ARCHIVOSCML")]
    public partial class archivosSolicitud
    {
        
        private inputSolicitudReporteValidacionEnvios entradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public inputSolicitudReporteValidacionEnvios entrada
        {
            get
            {
                return this.entradaField;
            }
            set
            {
                this.entradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DataTypes")]
    public partial class inputSolicitudReporteValidacionEnvios
    {
        
        private convenio convenioField;
        
        private string fechaGeneracionField;
        
        private string numeroEnvioField;
        
        private string tipoRendicionField;
        
        private string tipoArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public convenio convenio
        {
            get
            {
                return this.convenioField;
            }
            set
            {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaGeneracion
        {
            get
            {
                return this.fechaGeneracionField;
            }
            set
            {
                this.fechaGeneracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string numeroEnvio
        {
            get
            {
                return this.numeroEnvioField;
            }
            set
            {
                this.numeroEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoRendicion
        {
            get
            {
                return this.tipoRendicionField;
            }
            set
            {
                this.tipoRendicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoArchivo
        {
            get
            {
                return this.tipoArchivoField;
            }
            set
            {
                this.tipoArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DataTypes")]
    public partial class convenio
    {
        
        private string cuitField;
        
        private producto productoField;
        
        private string numeroField;
        
        private string descripcionField;
        
        private string monedaField;
        
        private cuenta cuentaField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuit
        {
            get
            {
                return this.cuitField;
            }
            set
            {
                this.cuitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public producto producto
        {
            get
            {
                return this.productoField;
            }
            set
            {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public cuenta cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DataTypes")]
    public partial class producto
    {
        
        private string tipoProductoField;
        
        private string numeroField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoProducto
        {
            get
            {
                return this.tipoProductoField;
            }
            set
            {
                this.tipoProductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CML")]
    public partial class inputarchivosPublicacions
    {
        
        private convenio convenioField;
        
        private byte[] archivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public convenio convenio
        {
            get
            {
                return this.convenioField;
            }
            set
            {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DataTypes")]
    public partial class retorno
    {
        
        private string codigoField;
        
        private string[] mensajeField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://DataTypes")]
    public partial class cuenta
    {
        
        private string principalField;
        
        private string deComisionField;
        
        private string deProductoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deComision
        {
            get
            {
                return this.deComisionField;
            }
            set
            {
                this.deComisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deProducto
        {
            get
            {
                return this.deProductoField;
            }
            set
            {
                this.deProductoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CML/ARCHIVOSCML")]
    public partial class archivosSolicitudResponse
    {
        
        private retorno retornoField;
        
        private byte[] attachField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public retorno retorno
        {
            get
            {
                return this.retornoField;
            }
            set
            {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[] attach
        {
            get
            {
                return this.attachField;
            }
            set
            {
                this.attachField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archivosSolicitudRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CML/ARCHIVOSCML", Order=0)]
        public ArchivosCmlServiceItau.archivosSolicitud archivosSolicitud;
        
        public archivosSolicitudRequest()
        {
        }
        
        public archivosSolicitudRequest(ArchivosCmlServiceItau.archivosSolicitud archivosSolicitud)
        {
            this.archivosSolicitud = archivosSolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archivosSolicitudResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CML/ARCHIVOSCML", Order=0)]
        public ArchivosCmlServiceItau.archivosSolicitudResponse archivosSolicitudResponse;
        
        public archivosSolicitudResponse1()
        {
        }
        
        public archivosSolicitudResponse1(ArchivosCmlServiceItau.archivosSolicitudResponse archivosSolicitudResponse)
        {
            this.archivosSolicitudResponse = archivosSolicitudResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CML/ARCHIVOSCML")]
    public partial class archivosPublicacion
    {
        
        private inputarchivosPublicacions entradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public inputarchivosPublicacions entrada
        {
            get
            {
                return this.entradaField;
            }
            set
            {
                this.entradaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://CML/ARCHIVOSCML")]
    public partial class archivosPublicacionResponse
    {
        
        private retorno retornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public retorno retorno
        {
            get
            {
                return this.retornoField;
            }
            set
            {
                this.retornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archivosPublicacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CML/ARCHIVOSCML", Order=0)]
        public ArchivosCmlServiceItau.archivosPublicacion archivosPublicacion;
        
        public archivosPublicacionRequest()
        {
        }
        
        public archivosPublicacionRequest(ArchivosCmlServiceItau.archivosPublicacion archivosPublicacion)
        {
            this.archivosPublicacion = archivosPublicacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archivosPublicacionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CML/ARCHIVOSCML", Order=0)]
        public ArchivosCmlServiceItau.archivosPublicacionResponse archivosPublicacionResponse;
        
        public archivosPublicacionResponse1()
        {
        }
        
        public archivosPublicacionResponse1(ArchivosCmlServiceItau.archivosPublicacionResponse archivosPublicacionResponse)
        {
            this.archivosPublicacionResponse = archivosPublicacionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ARCHIVOSCMLChannel : ArchivosCmlServiceItau.ARCHIVOSCML, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class ARCHIVOSCMLClient : System.ServiceModel.ClientBase<ArchivosCmlServiceItau.ARCHIVOSCML>, ArchivosCmlServiceItau.ARCHIVOSCML
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ARCHIVOSCMLClient() : 
                base(ARCHIVOSCMLClient.GetDefaultBinding(), ARCHIVOSCMLClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ARCHIVOS_ARCHIVOSCMLHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ARCHIVOSCMLClient(EndpointConfiguration endpointConfiguration) : 
                base(ARCHIVOSCMLClient.GetBindingForEndpoint(endpointConfiguration), ARCHIVOSCMLClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ARCHIVOSCMLClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ARCHIVOSCMLClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ARCHIVOSCMLClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ARCHIVOSCMLClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ARCHIVOSCMLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosSolicitudResponse1> ArchivosCmlServiceItau.ARCHIVOSCML.archivosSolicitudAsync(ArchivosCmlServiceItau.archivosSolicitudRequest request)
        {
            return base.Channel.archivosSolicitudAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosSolicitudResponse1> archivosSolicitudAsync(ArchivosCmlServiceItau.archivosSolicitud archivosSolicitud)
        {
            ArchivosCmlServiceItau.archivosSolicitudRequest inValue = new ArchivosCmlServiceItau.archivosSolicitudRequest();
            inValue.archivosSolicitud = archivosSolicitud;
            return ((ArchivosCmlServiceItau.ARCHIVOSCML)(this)).archivosSolicitudAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosPublicacionResponse1> ArchivosCmlServiceItau.ARCHIVOSCML.archivosPublicacionAsync(ArchivosCmlServiceItau.archivosPublicacionRequest request)
        {
            return base.Channel.archivosPublicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArchivosCmlServiceItau.archivosPublicacionResponse1> archivosPublicacionAsync(ArchivosCmlServiceItau.archivosPublicacion archivosPublicacion)
        {
            ArchivosCmlServiceItau.archivosPublicacionRequest inValue = new ArchivosCmlServiceItau.archivosPublicacionRequest();
            inValue.archivosPublicacion = archivosPublicacion;
            return ((ArchivosCmlServiceItau.ARCHIVOSCML)(this)).archivosPublicacionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ARCHIVOS_ARCHIVOSCMLHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ARCHIVOS_ARCHIVOSCMLHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://wesbhomol.sis.ad.bia.itau/CMLWeb/sca/ARCHIVOS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ARCHIVOSCMLClient.GetBindingForEndpoint(EndpointConfiguration.ARCHIVOS_ARCHIVOSCMLHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ARCHIVOSCMLClient.GetEndpointAddress(EndpointConfiguration.ARCHIVOS_ARCHIVOSCMLHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ARCHIVOS_ARCHIVOSCMLHttpPort,
        }
    }
}
